export const SPINNER_SPREADSHEET_ID = 'SPINNER_SPREADSHEET_ID';
export const SPINNER_SHEET_ID = 'SPINNER_SHEET_ID';
export const SPINNER_CLIENT_EMAIL = 'SPINNER_CLIENT_EMAIL';
export const SPINNER_PRIVATE_KEY = "SPINNER_PRIVATE_KEY";
